### ISSUE TITLE
Security 향후 계획

### ISSUE THREAD

**Issue by ryankimjh00** [Team-Discipline/URLS3-backend#3]
# Todo List(URLS3 Security team)🫠
- [x] **Session Hijacking and Man-in-the-Middle Attacks**
	- [x] **HSTS**
		- Using Django Security middleware
		- Using HTTP header 
- [ ] **XSS(Cross-Site Scripting)**
	- setting up a web application firewall(WAP)
	- Using HTTP header
	https://blog.techguard.com/how-to-prevent-xss-in-python-based-web-applications
	https://www.stackhawk.com/blog/django-xss-examples-prevention/
~~**Malware**~~
	- ~~virus~~
	- ~~ransomware~~
	      ~~https://cheapsslsecurity.com/blog/how-to-prevent-malware-attacks/~~
- [ ] **Phishing**
  - [ ] build CAPCHA
- [ ] **Path traversal**(no plans yet)
- [ ] **Local file inclusion**(no plans yet)
- [ ] **XML external entity (XXE)**(no plans yet)
- [x] **SSL /TLS**
	- Cryptography
	- https://kaizen8501.tistory.com/147
	- setting Django SSL server https://intrepidgeeks.com/tutorial/apply-django-ssl
	- CA(인증기관) 인증서 발급 받아서 사용(Domain필요함)

## **Tech Stack**💻
- **These tools are what we can use to prepare for unexpected attacks.**
	With python hidden Libs
	->Link: https://towardsdatascience.com/5-hidden-python-libraries-for-cyber-security-e83928777a95
	Nmap(To check network status)
	->Link: https://pypi.org/project/python-nmap/
	Scapy(to get an additional list of mismatched (unanswered) packets)
	->Link: https://scapy.readthedocs.io/en/latest/introduction.html
	Cryptography (for encryption)
	->Link: https://www.rapid7.com/fundamentals/types-of-attacks/

Django Security middleware 
https://docs.djangoproject.com/en/4.1/ref/middleware/#module-django.middleware.security

HTTP header
https://blog.heroku.com/using-http-headers-to-secure-your-site

~~## **FireWall** 👨‍💻
I think building a firewall on our own is seriously difficult, so we need to use a library someone made.
If we user firewall, we can prevent ***malware** attacks at the start
https://github.com/0xInfection/Awesome-WAF#operation-modes
This library got 4600 Stars✨~~

~~Or use this library https://github.com/EnableSecurity/wafw00f#how-do-i-install-it. This library got 3600 stars✨ and it has simple descriptions~~

## **Schedules** 👨‍💻
- [ ] Build WAF with the library we chose
- [x] Start with setting HTTP headers
- [ ] ~~getting TLS(SSL) key(상대방꺼 TSL 연결이 되었는지)~~
- [ ] Making policy for our website
- [x] Find out how to check the HTTP communication itself, including the user's js file.
and so on...

@kreimben @JungHanLeee @ss35789 @gka0903 @gyuriiiii @b22016645

**Comment by ryankimjh00** [comment]
이슈 수정(스케쥴 추가)

**Comment by ryankimjh00** [comment]
Django 
https://docs.djangoproject.com/en/4.1/intro/

DRF
Turorial(https://www.django-rest-framework.org/tutorial/quickstart/)
Requests
Responses
Views
Viewsets
Serializers
Authentication
Metadata
Schemas

**Comment by ryankimjh00** [comment]
### 오늘 미팅 내용 정리
위의 `Django`와 `Django REST Framework` 의 공부 순서는 미팅에서 설명했던 대로입니다. `DRF`는 되도록 모든 documents를 공부 해야 하지만 위의 항목들은 우리 프로젝트에서 필수적으로 사용되므로 우선적으로 학습해야 합니다. **URLS3 security**에 관한 내용은 `schedules` 목록에 맞춰 공부 순서를 지켜 나가면 됩니다. 학기가 시작되어 다들 무척 바쁠 것으로 예상되나 DRF 까지는 이번주 일요일 까지 최대한 빨리 학습을 진행해 주시기를 바랍니다. `Django` 골격에 대해 이해가 없다면 다른 라이브러리들을 적용하는데 어려움이 있기 때문입니다. 저도 공부를 하고 있으니 계획에서 수정 사항이 생기거나 추가로 알아야 할 부분이 있으면 지속적으로 수정하고 멘션을 하겠습니다. 또 제가 잘못 정한 계획이나 오류, 혹은 의견이 있으면 저를 맨션 해주세요. 같이 열심히 해봐요!! 화이팅📣:)

p.s) 아까 미팅에서 규칙을 정립했던 것 같이 이 댓글을 읽으면 오른쪽 위에 얼굴 표시에서 👀 을 누르거나 읽었다는 표시만 해주시면 감사하겠습니다.
@JungHanLeee @b22016645

**Comment by ryankimjh00** [comment]
Web Application Firewall에 대한 조사가 좀 더 필요한 관계로 순서를 변경합니다.

1. XSS - Cross site scipting 공격 해결
	- 특정 요소들을 회피하는 방향으로 해결(escaping specific characters)
	- django Automatic HTML escaping [Link](https://docs.djangoproject.com/en/4.0/ref/templates/language/#automatic-html-escaping)
2. Clickjacking protection
	- django는 clickjacking 을 보호하는 기능을 갖고 있음( `X-Frame-Options middleware`)
	- django security middleware [Here](https://docs.djangoproject.com/en/4.0/ref/middleware/#module-django.middleware.security) 
	- [`<frame>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/frame), [`<iframe>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe), [`<embed>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/embed) or [`<object>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/object) 요소를 검사해야함
3. Enforcing SSL/HTTPS
	-  `SECURE_SSL_REDIRECT`  [Here](https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-SECURE_SSL_REDIRECT)
	-  `SECURE_PROXY_SSL_HEADER`  [Here](https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-SECURE_PROXY_SSL_HEADER)
	-  HSTS
4. HSTS
	-  [HTTP Strict Transport Security](https://docs.djangoproject.com/en/4.0/ref/middleware/#http-strict-transport-security)
	-  [`SECURE_HSTS_SECONDS`](https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-SECURE_HSTS_SECONDS) and [`SECURE_HSTS_INCLUDE_SUBDOMAINS`](https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-SECURE_HSTS_INCLUDE_SUBDOMAINS)
	-  Secure Cookie [`SESSION_COOKIE_SECURE`](https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-SESSION_COOKIE_SECURE) and [`CSRF_COOKIE_SECURE`](https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-CSRF_COOKIE_SECURE)
5. 비밀번호 암호화 하여 저장(?)
6. WAF


참고:
Server side web application security
https://developer.mozilla.org/en-US/docs/Web/Security

**Comment by kreimben** [comment]
@ryankimjh00 

# Define the way how to check user input urls' security.
i.e.) middleware or just functions...

**Comment by ryankimjh00** [comment]
> @ryankimjh00
> 
> # Define the way how to check user input urls' security.
> i.e.) middleware or just functions...

Got it👀

**Comment by kreimben** [comment]
# Pair Programming Wrap-ups.

1. HSTS Code [here](https://gist.github.com/kisom/3219483)
2. XSS Attack library [here](https://github.com/s0md3v/XSStrike)
3.

**Comment by kreimben** [comment]
@kreimben 
결론 -> hsts랑 xss만 추가하면 될듯.

**Comment by kreimben** [comment]
# FE Should Implement That

1. target url
2. and should ask to go to there
